### ISSUE TITLE
Mangler informasjon om støtteteam 

### ISSUE THREAD

**Issue by olavflar** [digdir/baksia#201]
Mangler informasjon her 

https://baksia.digdir.no/brukeropplevelse-og-datadeling/team/

<img width="1408" alt="Screenshot 2023-07-05 at 09 33 29" src="https://github.com/digdir/baksia/assets/70377508/c73d1216-8e1d-449f-92c5-305cdccdff2b">

**Comment by altinnadmin** [comment]
https://baksia.digdir.no/teams/#enabling
