### ISSUE TITLE
Responsive layout on boxes 

### ISSUE THREAD

**Issue by olavflar** [digdir/baksia#202]
From 991px  to 1199px width the text floats out of the div box 
Example: 
<img width="890" alt="Screenshot 2023-07-05 at 11 18 46" src="https://github.com/digdir/baksia/assets/70377508/8cfc8c8c-ce26-439d-bf02-6ce1699c5dfd">

https://baksia.digdir.no/brukeropplevelse-og-datadeling/produkter/

**Comment by altinnadmin** [comment]
Seems to be fixed. Closes this.

![image](https://github.com/digdir/baksia/assets/6088624/95ad353e-f150-4e9c-b0f0-ba61db15423e)
