### ISSUE TITLE
Dokumentere forretningsflyt(As is)

### ISSUE THREAD

**Issue by HanneLauritsen1967** [digdir/baksia#548]
Har laget et utkast i vedlagte presentasjon

[forretningsflyt.pptx](https://github.com/digdir/baksia/files/15479891/forretningsflyt.pptx)

```[tasklist]
### Tasks
- [x] Identifisere hvilke skisser vi må etablere
```

**Comment by fsveinsb** [comment]
@MrCarrera Har da laget et forslag, kan du ta en kikk på dette?
