### ISSUE TITLE
Etablere initiell prosess struktur

### ISSUE THREAD

**Issue by HanneLauritsen1967** [digdir/baksia#549]
```[tasklist]
### Tasks
- [ ] Opprette en struktur for lagring av dokumentasjon (Før det legges ut på baksia)
```

**Comment by altinnadmin** [comment]
@HanneLauritsen1967 Denne ble jo skjult før jul, er det et utgangspunkt? https://github.com/digdir/baksia/tree/main/content/brukeropplevelse-og-datadeling/prosesser
