### ISSUE TITLE
Portfolio description (test)

### ISSUE THREAD

**Issue by MrCarrera** [digdir/baksia#608]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

- [x] Test 1 2 3
- [x] Test 123

```[tasklist]
### Tasks
```

**Comment by fsveinsb** [comment]
Dette tiltaket er ikke tilstrekkelig avklart. Dette lukkes
