### ISSUE TITLE
Workshop:Understanding and Improving Current Processes and Workflows at Digdir

### ISSUE THREAD

**Issue by MrCarrera** [digdir/baksia#622]
Agenda til WS: 

Description:
This epic aims to identify and understand the current processes and workflows at Digdir/BOD, with a specific focus on portfolio management, the "Modernisering av Altinn" project, and how teams deliver through the backlog to the portfolio. Based on this understanding, we will map out the current operational flow ("as is") to identify areas for improvement and increase organizational efficiency.

The goals are to answer below questions:

1. Hvem er målgruppen for vårt arbeid som dokumenteres på baksia.digdir.no?
2. Hvordan henger baksia sammen med intranet (digdir.sharepoint.com), samarbeid.digdir.no, docs.altinn.studio, pedia.altinn.cloud og designsystemet.no?
3. Hvordan prioriterer vi arbeid i BOD?
4. Hvordan jobber vi med å løse oppgaver i BOD?
5. Hvordan håndterer vi risiko i BOD?

**Workshop agenda (In progress):**

Total Duration: 7 hours (including 30 min lunch)

Workshop Agenda (Revised)
Total Duration: 6 hours (including 1-hour lunch)

**1. Velkommen**
Tid: 09:00 - 09:15 (15 minutter)

**Introduksjon og formål med workshopen.**

3. 2. Gjennomgang av dagens agenda og mål.
Tid: 09:15 - 10:00 (45 minutter)

- Hva/hvorfor samles vi i et team? (Visjon, warm up, rund table)
- OKR for teamet - gjennomgang og revisjon

**Del 1: Bli enig om overordnet struktur på baksia - nettsted kart med nivåer**

Tid: 10:00 - 10:45 (45 minutter)

- Identifisere de ulike delene og teamene som har behov for å dokumentere informasjon som de skal formidle

**Del 2: Identifisere flyten fra portefølje til produksjon og tilbake**

Tid: 10:45 - 11:30 (45 minutter)

- - Ta utgangspunkt i eksisterende beskrivelser som ligger her:
https://github.com/digdir/portfolio
https://baksia.digdir.no/brukeropplevelse-og-datadeling/team/enabling/portefoeljestyring/

- Identifisere seremoniene som brukes.
- Identifisere de ulike rollene og funksjonene i porteføljestyringen og hvordan disse spiller sammen i seremoniene.
- Dokumenterer og visualisere flyten

**Lunsjpause
Tid: 11:30 - 12:15 (45 minutter)**

**Del 3: Identifisere hvordan teamene leverer gjennom backloggen mot porteføljen/Programmet Modernisering av Altinn**
Tid: 12:15 - 13:30 (1 time og 15 minutter)

Ta utgangspunkt i ekisterende beskrivelser i altinn pedia og altinn docs.

- Utforske hvordan teamene jobber med backloggen og kartlegg arbeidsflyten, mandatet og rollene 
- Identifisere seremoniene og tidshorisonten for operasjonene i hvert team, samt kapasitet allokering.
- Identifisere seremonier og samarbeidsfora for koordinering av arbeid i mellom team
- Identifisere prosjektets rolle opp mot team og portefølje
- Diskutere leveringsprosessen mot porteføljen/programmet/prosjektet.
- Dokumenter og visualiser flyten

Pause
Tid: 13:30 - 13:45 (15 minutter)

**Oppsummering og "As is"-flyt**
Tid: 13:45 - 15:30 (1 t 45 min)
Tegne opp den nåværende totale operasjonelle flyten basert på funnene og de tidligere visualiseringene.

**Avslutning
Tid: 15:30 **

**Comment by MrCarrera** [comment]
[1.docx](https://github.com/digdir/baksia/files/15389630/1.docx)

Support material for the Workshop

**Comment by andreas-rafaelsen** [comment]
Selvfølgelig! Her er tre OKRs (Objectives and Key Results) for deres produktutviklingsteam for å dokumentere Product Operating Model:
### Objective 1: Forbedre Dokumentasjonskvaliteten for Product Operating Model
- **KR1:** Fullføre en omfattende gjennomgang og oppdatering av eksisterende dokumentasjon innen utgangen av kvartalet.
- **KR2:** Implementere en standardisert dokumentasjonsmal og sikre at alle avsnitt i modellen følger denne malen.
- **KR3:** Få dokumentasjonen gjennomgått og godkjent av minst tre nøkkelinteressenter innen kvartalet.
### Objective 2: Øke Tilgjengeligheten og Bruken av Dokumentasjonen
- **KR1:** Publisere den oppdaterte Product Operating Model-dokumentasjonen på en lett tilgjengelig intern plattform innen utgangen av kvartalet.
- **KR2:** Organisere minst to treningsøkter for teammedlemmer og relevante interessenter for å forklare den oppdaterte dokumentasjonen innen kvartalet.
- **KR3:** Oppnå minst 80% tilfredshet fra treningsøktene, målt gjennom etterfølgende spørreundersøkelser.
### Objective 3: Sikre Kontinuerlig Oppdatering og Forbedring av Dokumentasjonen
- **KR1:** Etablere en prosess for regelmessig gjennomgang og oppdatering av dokumentasjonen, inkludert ansvarlige teammedlemmer og en fast tidsplan.
- **KR2:** Integrere tilbakemeldingsmekanismer slik at brukere kan gi forslag til forbedringer, og håndtere minst 90% av tilbakemeldingene innen én måned etter mottak.
- **KR3:** Sikre at dokumentasjonen er oppdatert minst en gang per kvartal, med tydelig dokumenterte endringer og oppdateringslogg.
Disse OKRene vil hjelpe teamet ditt med å strukturere arbeidet med å dokumentere Product Operating Model, samt sikre at dokumentasjonen er nyttig, oppdatert, og lett tilgjengelig for alle relevante parter.

**Comment by altinnadmin** [comment]
Workshop has been held, closes this
