### ISSUE TITLE
Document operational routines

### ISSUE THREAD

**Issue by andreas-rafaelsen** [digdir/baksia#626]
> @HanneLauritsen1967: påstartet. Må oversettes til norsk og gjøre en ekstra QA på om det er noe mer som mangler

https://baksia.digdir.no/produktutviklingsmodell/prinsipper/operations/

**Comment by MrCarrera** [comment]
@HanneLauritsen1967 are you workig on this? If not, can you move it back to NonStatus? If done, or not relevant move it to "close"

**Comment by HanneLauritsen1967** [comment]
https://baksia.digdir.no/produktutviklingsmodell/prinsipper/ops/ mye er dok her

**Comment by HanneLauritsen1967** [comment]
påstartet. Må oversettes til norsk og gjøre en ekstra QA på om det er noe mer som mangler

**Comment by HanneLauritsen1967** [comment]
oppdatert til norsk og gjennomført QA
