### ISSUE TITLE
Describe Portfolio process (content)

### ISSUE THREAD

**Issue by andreas-rafaelsen** [digdir/baksia#627]

**Comment by MrCarrera** [comment]
We need a better description for this issue

**Comment by altinnadmin** [comment]
@fsveinsb Starting point: https://baksia.digdir.no/produktutviklingsmodell/portfolio/

**Comment by MrCarrera** [comment]
This is solved for V1 portfolio content. https://baksia.digdir.no/produktutviklingsmodell/portfolio/
