### ISSUE TITLE
Describe Devops methods and principles

### ISSUE THREAD

**Issue by andreas-rafaelsen** [digdir/baksia#630]

**Comment by HanneLauritsen1967** [comment]
In progress, will be finished in week 26

**Comment by HanneLauritsen1967** [comment]
In progress, will be finished in week 26/27

**Comment by altinnadmin** [comment]
- Placeholder for DevOps: https://baksia.digdir.no/produktutviklingsmodell/devops/
- Placeholder for Ops-principles: https://baksia.digdir.no/produktutviklingsmodell/prinsipper/ops/

**Comment by MrCarrera** [comment]
@HanneLauritsen1967  Is this done here: https://baksia.digdir.no/produktutviklingsmodell/prinsipper/ops/
If so, please move the item to "done"
