### ISSUE TITLE
Create flow map for POM

### ISSUE THREAD

**Issue by andreas-rafaelsen** [digdir/baksia#633]
Add flow map for the flow of issues trough the PoM

**Comment by andreas-rafaelsen** [comment]
[PoM Flow.pptx](https://github.com/user-attachments/files/15543183/PoM.Flow.pptx)
Added PoM flow ppt

**Comment by andreas-rafaelsen** [comment]
Kan du se på denne og lage en finere @sorensensig  ? :-)

**Comment by andreas-rafaelsen** [comment]
Topp :-) Jeg synes denne kommuniserer, hva tenker dere @fsveinsb og @altinnadmin  ?

**Comment by MrCarrera** [comment]
@sorensensig Har vi mulighet til å representere på en måte at "alle", "hvem som helst" kan ta saker til portefølje i tillegg til Ledese og Program?

**Comment by sorensensig** [comment]
**Update:**
@MrCarrera, @andreas-rafaelsen se om denne utgaven egner seg bedre :) 

![Image](https://github.com/digdir/baksia/assets/32162632/4e0dd980-f454-4b29-80bf-5c40d4094107)

**Comment by andreas-rafaelsen** [comment]
KJempebra :-)

**Comment by altinnadmin** [comment]
Publisert: https://baksia.digdir.no/produktutviklingsmodell/
