### ISSUE TITLE
Create documentation site overview

### ISSUE THREAD

**Issue by andreas-rafaelsen** [digdir/baksia#635]
Har laget en oversikt som viser sammenhenger mellom de ulike sitene. 

[documentation site overview.pptx](https://github.com/digdir/baksia/files/15479404/documentation.site.overview.pptx)

Viktig å enes om en overordnet modell før vi jobber videre med de detaljerte innspill

**Comment by fsveinsb** [comment]
@MrCarrera En avklaring på denne oppgaven: Jeg skal lage et kart som viser sammenhengen mellom samarbeidsportalen, baksida, https://altinn.github.io//docs og https://docs.altinn.studio/ - eller (?)

**Comment by fsveinsb** [comment]
@MrCarrera Du får reåpne hvis dette ikke var som forventet
