### ISSUE TITLE
Define management/organizations structure placenment and illustrate

### ISSUE THREAD

**Issue by andreas-rafaelsen** [digdir/baksia#636]
Illustrate and describe how the management/organizations structure aligns with the PoM and the product organization

**Comment by andreas-rafaelsen** [comment]
[Management vs POM.pptx](https://github.com/user-attachments/files/15567545/Management.vs.POM.pptx)
@sorensensig  Om disse figurene visualiseres med samme enkle form som du brukte på den andre figuren er kanskje dette tilstrekkelig innhold ?

@altinnadmin  Hva tenker du ?

**Comment by sorensensig** [comment]
**Utkast:** @andreas-rafaelsen 

![POM og Seksjoner](https://github.com/digdir/baksia/assets/32162632/ba3e9c4c-f09e-47c1-a268-75b305982118)
![Team Typologies - eksempel](https://github.com/digdir/baksia/assets/32162632/745caf34-0bf6-489e-8982-15708d0154da)
![Team Typologies - Interaksjon modus](https://github.com/digdir/baksia/assets/32162632/396745f1-58b6-400a-8ff6-7ee2bb8b407c)
![Team Typologies - team typer](https://github.com/digdir/baksia/assets/32162632/1bc0ac3e-bbe3-49ad-a9d4-cc65d30fd2ee)

**Comment by andreas-rafaelsen** [comment]
Hei jeg synes dette gir mening :-) Veldig bra

**Comment by MrCarrera** [comment]
@sorensensig : Change name from DAIS - Platform team.

**Comment by sorensensig** [comment]
@MrCarrera, illustration showing DAIS have been changed. These items (v1) are now ready for publishing. svg versions (v2) of the files alongside mobile versions will be uploaded to a seperate issue. #652 once they are ready.
