### ISSUE TITLE
Describe user experience principles

### ISSUE THREAD

**Issue by sorensensig** [digdir/baksia#638]
Principles for Design is work in progress, where the current version is listed below:
[source](https://miro.com/app/board/uXjVN5ti8IY=/)

```
1.Sett brukernes behov først
2.Skjul kompleksitet
3.Del opp kompliserte oppgaver.
4.Sørg for at tjenesten er tilgjengelig for alle
5.Skap helhet
•Innbyggerne skal få en helhetlig brukeropplevelse.
•Konsekvent språk og samme gjenkjennbare komponenter på tvers av løsninger.
•Brukerne skal slippe å lære seg noe nytt dersom de har gjort noe liknende et annet sted.
6.Bruk etablerte interaksjonsmønstre
•Følge prinsipper for interaksjonsdesign brukere kjenner til fra før.
•Bruke fellesløsninger og være med på å videreutvikle dem når tjenestene designes.
7.La brukeren løse oppgaven i den konteksten hvor behovet oppstår.
```

**Comment by MrCarrera** [comment]
@sorensensig What is the content that will be published in baksida? Is it the list? 
To everyone:  Look at the design principles, how many of those principles do we cover when building baksida?

**Comment by sorensensig** [comment]
@MrCarrera Yes, these are the first version of our design principles. They do not cover user experience QA requirements / principles which will be added later on.

**Comment by altinnadmin** [comment]
Publisert: https://baksia.digdir.no/produktutviklingsmodell/prinsipper/design/
