### ISSUE TITLE
Update Baksia with information and descriptions of OKR cycles

### ISSUE THREAD

**Issue by sorensensig** [digdir/baksia#639]
Ref: Assigned key result underneath the first OKR in futureworks for the OKR ambassadors.

**Comment by HanneLauritsen1967** [comment]
In progress, will be finished in week 26

**Comment by MrCarrera** [comment]
General description about how we do work with OKRs within the product teams

**Comment by altinnadmin** [comment]
@HanneLauritsen1967 Here is the placeholder: https://baksia.digdir.no/produktutviklingsmodell/okr/

**Comment by MrCarrera** [comment]
I have created the first draft of OKRs. Please @HanneLauritsen1967 have a look and change if needed. 
I used the presentation: Digdir OKRs kickstart- 

See current Source_ https://baksia.digdir.no/produktutviklingsmodell/okr/ 


[OKR kickstart (1).pptx](https://github.com/user-attachments/files/16752440/OKR.kickstart.1.pptx)

**Comment by MrCarrera** [comment]
Moved to done as it is published already.
