### ISSUE TITLE
Drift og vedlikehold

### ISSUE THREAD

**Issue by fsveinsb** [digdir/baksia#642]
Det må avklares hvordan drift, vedlikehold og forvaltning av løsning skal utføres og som en helhet i produktutvikling devOps.

Det er to områder som bør avklares, 
- Hvordan sikrer en at ansvar er ivaretatt?
- Hvordan sikrer en at oppgaver utføres som tiltenkt?

**Comment by HanneLauritsen1967** [comment]
Denne er dokumentert i et annet issue
