### ISSUE TITLE
Create the initial Sitemap of Baksia

### ISSUE THREAD

**Issue by sorensensig** [digdir/baksia#697]
**Describe the problem**
To ensure more directed and wholesome conversations revolving content and structure on Baksia, a sitemap should be established.

**Describe the solution**
The link below points to a living document in figma, meaning it will evolve over time.
[Sitemap (figma / living document)](https://www.figma.com/design/oT5ZgqREUJGgYwXIgp3HWL/Baksia?node-id=4985-43319&t=M3inVrCddhG3c1jw-1)

**Comment by MrCarrera** [comment]
@sorensensig How do you want to have this issue Sigurd? Still open as Draft? or splitt into version so it can be closed and reopen a new one when you have version 2 for instance?

**Comment by altinnadmin** [comment]
Implemented in [#819](https://github.com/digdir/baksia/pull/819), closes this issue.
