### ISSUE TITLE
Improve content as flow chart is not self self explanatory

### ISSUE THREAD

**Issue by sorensensig** [digdir/baksia#698]
As a reader of bakisa, I found difficult to understand the meaning of the flow as the graph is not self explanatory. To understand it, I would like to have som text explaining what are all those connectors, and boxes. The flow graph is in good support, but without the explanation I dont understand it.  

Source: https://baksia.digdir.no/produktutviklingsmodell/
![Image](https://github.com/user-attachments/assets/f9a21742-737e-4f85-bc43-c63c1d49197b)

**Comment by sorensensig** [comment]
@MrCarrera, 

Take a look at [this](https://www.figma.com/design/oT5ZgqREUJGgYwXIgp3HWL/Baksia?node-id=5022-37986&t=3LWN4UZ3En3vkNOH-1) as an alternative to the POM Flow illustrations from before.

The resource allocation illustration will get its own page eventually as well in the same fashion.

**Comment by altinnadmin** [comment]
Should be described in the new pages under https://baksia.digdir.no/produktutviklingsmodell/flyt/

Will create new issues, closing this.
