### ISSUE TITLE
Update site so all leaders are visible according to new org.

### ISSUE THREAD

**Issue by andreas-rafaelsen** [digdir/baksia#702]
Source: https://baksia.digdir.no/teams/lederlaget/
Shows: Missing Bjørn, and Gruppe leder. Titles are not updated after changes in the organization. 

![Image](https://github.com/user-attachments/assets/7eff4c9b-60f3-4f2c-b435-d9ed3631dc43)

Expected. Udate in "Medlemmer i teamet" for the Lederlaget (BOD)

**Comment by MrCarrera** [comment]
Bjørn er nå i listen etter jeg har oppdatert siden. Så stenger denne saken
