### ISSUE TITLE
Create text and content for space: https://baksia.digdir.no/produktutviklingsmodell/roller/

### ISSUE THREAD

**Issue by MrCarrera** [digdir/baksia#727]
Site is empty, with no explanation. 

![Image](https://github.com/user-attachments/assets/204cbf59-2e68-4b20-96b5-2bd1b86fe0c4)

**Comment by MrCarrera** [comment]
Fiksed: Update _index.md #728

**Comment by altinnadmin** [comment]
Now linking to internal site. Closing this.
