### ISSUE TITLE
Added content to arkitektur principles as it was empty with two links

### ISSUE THREAD

**Issue by MrCarrera** [digdir/baksia#735]
Added content to this page as it was emplty. Please review @altinnadmin 
Source: https://baksia.digdir.no/produktutviklingsmodell/prinsipper/arkitektur/

![Image](https://github.com/user-attachments/assets/e13fc305-82ba-4392-bde3-80a9e68c7533)

**Comment by MrCarrera** [comment]
Fixed: Update index.md #734

**Comment by altinnadmin** [comment]
> Please review @altinnadmin

Reviews are done on a PR before merging, but you merged the changes right away, no chance to do a review...

**Comment by altinnadmin** [comment]
Closes this, will add new issue for updating arch principles
