### ISSUE TITLE
Create new team type on the teams page

### ISSUE THREAD

**Issue by sorensensig** [digdir/baksia#804]
**Is your feature request related to a problem? Please describe.**
Some teams on the teams page do not adhere to the team typologies framework and should be identified in a different way from the other teams.

**Describe the solution you'd like**

```[tasklist]
### Tasks
- [x] Establish a new team type called "Andre team og faggrupper"
- [x] Move the following over to the new team type: "OKR Ambassadører", "Porteføljekontor" and "Prosjektkontor"
```

**Comment by altinnadmin** [comment]
Fixed by #824
