### ISSUE TITLE
Fylle ut tekst på Flyt-siden

### ISSUE THREAD

**Issue by andreas-rafaelsen** [digdir/baksia#809]
I hht nytt design

**Comment by altinnadmin** [comment]
@sorensensig Consider if there should be more text her, or of the text should be at the level below instead. Ref. #812, #810 and #811.

https://baksia.digdir.no/produktutviklingsmodell/flyt/

**Comment by sorensensig** [comment]
@altinnadmin, I've updated the design for this page now ([link to figma](https://www.figma.com/design/oT5ZgqREUJGgYwXIgp3HWL/Baksia?node-id=5463-14794&m=dev&focus-id=5500-22369)).
