### ISSUE TITLE
Fylle ut tekst på Team-saker

### ISSUE THREAD

**Issue by andreas-rafaelsen** [digdir/baksia#810]
I hht tekst i fra figma

**Comment by sorensensig** [comment]
@altinnadmin, I made some changes to your suggestion in a updated wireframe ([figma link](https://www.figma.com/design/oT5ZgqREUJGgYwXIgp3HWL/Baksia?node-id=5463-14794&m=dev&focus-id=5520-25856)).

**Disclaimer:** The styles are not a perfect re-creation of the live version, so if some measures are off, stick to what you have in the live version of the website.
