### ISSUE TITLE
Fylle ut tekst til Produktgruppe saker

### ISSUE THREAD

**Issue by andreas-rafaelsen** [digdir/baksia#812]
I hht forslag fra nytt design

**Comment by altinnadmin** [comment]
@sorensensig Added some text from Figma, have a look: 

https://baksia.digdir.no/produktutviklingsmodell/flyt/produktgruppe/

**Comment by sorensensig** [comment]
@altinnadmin , I made some changes to your suggestion in a updated wireframe ([figma link](https://www.figma.com/design/oT5ZgqREUJGgYwXIgp3HWL/Baksia?node-id=5463-14794&m=dev&focus-id=5520-26119)).

**Disclaimer:** The styles are not a perfect re-creation of the live version, so if some measures are off, stick to what you have in the live version of the website.
