### ISSUE TITLE
Oppdatere prinsipper for Brukeropplevelse

### ISSUE THREAD

**Issue by andreas-rafaelsen** [digdir/baksia#816]
Siden må oppdateres med prinsipper for brukeropplevelse:
https://baksia.digdir.no/produktutviklingsmodell/prinsipper/brukeropplevelse/

**Comment by sorensensig** [comment]
@altinnadmin , I made some changes to your suggestion in a updated wireframe ([figma link](https://www.figma.com/design/oT5ZgqREUJGgYwXIgp3HWL/Baksia?node-id=5463-14794&m=dev&focus-id=5540-34575)).

The template for Heuristic Evaluation is not ready yet and can be linked to when it is done.

**Disclaimer:** The styles are not a perfect re-creation of the live version, so if some measures are off, stick to what you have in the live version of the website.
