### ISSUE TITLE
Oppdatere prinsipper for Arkitektur

### ISSUE THREAD

**Issue by altinnadmin** [digdir/baksia#822]
Fiks denne https://baksia.digdir.no/produktutviklingsmodell/prinsipper/arkitektur/

**Comment by TeyStar** [comment]
Is this what was needed to be updated?

![Image](https://github.com/user-attachments/assets/5a748fd9-b101-404c-9a74-3beb467e73fc)

**Comment by altinnadmin** [comment]
> Is this what was needed to be updated?

@TeyStar Nope, this issue is for fixing content on the linked page. I'll do it.
