### ISSUE TITLE
Team produktutvikling

### ISSUE THREAD

**Issue by altinnadmin** [digdir/baksia#827]
Teamet mangler i oversikten

**Comment by MrCarrera** [comment]
Hei @altinnadmin I cannot create the hugo file with the placeholders for the team. Can you help me? I tried by creating new file with path /.../.../produktutviklingsmodell/index.md bit got a hugo error :/

**Comment by altinnadmin** [comment]
I've now added the team: https://baksia.digdir.no/teams/produktutvikling

**Comment by MrCarrera** [comment]
Than you @altinnadmin :)

**Comment by altinnadmin** [comment]
> Thank you @altinnadmin :)

@MrCarrera No prob :)
