### ISSUE TITLE
Information lacking on legal team page

### ISSUE THREAD

**Issue by sorensensig** [digdir/baksia#920]
**Is your feature request related to a problem? Please describe.**
The legal team page has a placeholder for information that is lacking.

https://baksia.digdir.no/teams/juridisk/

**Comment by altinnadmin** [comment]
@benedicteos Kan du liste opp ansvarsområdene for teamet ditt? :)

![image](https://github.com/user-attachments/assets/13460f2a-68bd-4205-a754-17962d52ba37)
