### ISSUE TITLE
WCAG issue 1.4.4: Resize Text and 1.4.10 Reflow

### ISSUE THREAD

**Issue by olavflar** [digdir/baksia#927]
Seems like all the navigation cards have a max width, when zooming in 200% The information will float outside of the nav-card. Check out this screenshot: ![Image](https://github.com/user-attachments/assets/0976c4d8-3aa5-4abe-a3ea-313c2be44980)

This is with zoom 400% 
![Image](https://github.com/user-attachments/assets/75f08818-c7b2-4e02-b4b3-2347ea39bee9)

**Comment by altinnadmin** [comment]
Fixed by #929.

200% text zoom:
![image of zoomed page](https://github.com/user-attachments/assets/1f0b299d-6f25-44fc-875f-1b6d1c501893)
